-- 1. Reset: Drop existing table and policies to start fresh
drop policy if exists "Users can manage their own cart items" on cart_items;
drop table if exists cart_items;

-- 2. Create Table
create table cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_id bigint not null,
  quantity integer default 1,
  size text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS
alter table cart_items enable row level security;

-- 4. Create Explicit Policies (Standard Approach)
-- Policy for SELECT (View own items)
create policy "Enable read access for users based on user_id"
on cart_items for select
using (auth.uid() = user_id);

-- Policy for INSERT (Add own items)
create policy "Enable insert for users based on user_id"
on cart_items for insert
with check (auth.uid() = user_id);

-- Policy for UPDATE (Update own items)
create policy "Enable update for users based on user_id"
on cart_items for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Policy for DELETE (Remove own items)
create policy "Enable delete for users based on user_id"
on cart_items for delete
using (auth.uid() = user_id);

-- 5. "High End" Approach: Server-Side Cart Sync Function (RPC)
-- This function runs securely on the database, bypassing client-side RLS quirks for batch operations.
create or replace function sync_cart(items jsonb)
returns void
language plpgsql
security definer -- Runs with admin privileges to ensure reliability
set search_path = public
as $$
declare
  item jsonb;
  uid uuid;
begin
  -- Get current authenticated user ID
  uid := auth.uid();
  
  -- Security check
  if uid is null then
    raise exception 'Not authenticated';
  end if;

  -- Iterate through items and insert
  for item in select * from jsonb_array_elements(items)
  loop
    -- Optional: Check if item exists to avoid duplicates (Upsert logic could go here)
    -- For now, we insert as requested.
    insert into cart_items (user_id, product_id, quantity, size)
    values (
      uid,
      (item->>'id')::bigint,
      (item->>'quantity')::int,
      item->>'size'
    );
  end loop;
end;
$$;

-- Grant execute permission to authenticated users
grant execute on function sync_cart(jsonb) to authenticated;
